### ISSUE TITLE
seismic-zfp 0.3.1

### ISSUE THREAD

**Issue by VitaminORA** [equinor/seismic-zfp#81]
Dear all, 
I've tryed to use seismic-zfp, version 0.3.1.
Firstly I've counted hash SGY file  (metod SHA-1).
928D578CE3E0EC6BDE8896872EB7431584F5877D
I've made compress SGY file and uncompress.
In the end I've counted hash SGY file after uncompress (metod SHA-1))
E64792B077C6CFC9CB5392C805C95E98803085FB
Files are different ???? Why ????
I used commands 
seismic-zfp sgy2sgz c:\Python\00\rr12.sgy  c:\Python\00\rr12.sgz --bits-per-voxel 4
seismic-zfp sgz2sgy c:\Python\00\rr12.sgz  c:\Python\00\rr12_sgz.sgy

**Comment by da-wad** [comment]
Because [ZFP ](https://computing.llnl.gov/projects/zfp )is [lossy compression](https://en.wikipedia.org/wiki/Lossy_compression).

Lossless compression is not supported by seismic-zfp, but it's likely your workflow will work absolutely fine with lossy compression. Do a numerical comparison of `rr12.sgy` and `rr12_sgz.sgy`, and you should find the differences are very small in comparison to the absolute values. If you find there are many large differences please open a new issue.
